### PR TITLE
Roman-Numeral-convertor ✨✨

### PR DESCRIPTION
**Pull request by WALWALASAFI**
Roman-Numeral-convertor ✨
A numeral Roman converter is a tool or program designed to convert numbers between Roman numerals and Arabic (decimal) numerals. Here’s a description of how such a converter typically functions and its utility:

Education and Learning: Useful for students learning about Roman numerals in history, mathematics, or classical studies. Practical Applications: Helps in understanding and interpreting historical documents, clocks, and other artifacts that use Roman numerals. Programming and Development: Often integrated into software development for tasks involving Roman numeral conversions, such as in financial software or historical data processing. Features: Error Handling: Typically includes validation to ensure correct input formats and ranges. User-Friendly Interface: Provides clear instructions and feedback for users.

### CODE REVIEW

**Comment by ahzamir** [comment]
@WALWALASAFI 

- I can not see your partner's feedback

**Comment by WALWALASAFI** [comment]
Dear @ZohalMirkhel,
have a look at this project  darling

**Comment by WALWALASAFI** [comment]
check the code

**Comment by ZohalMirkhel** [comment]
Dear @WALWALASAFI, I reviewed your project, and it is functioning properly. However, your JavaScript code did not pass the linter checks. The errors are mainly due to the use of var instead of let and const. Additionally, your HTML code could be cleaner. Consider using double spaces instead of four spaces or tabs for indentation. 

Thank You!

**Comment by WALWALASAFI** [comment]
@ZohalMirkhel i have corrected the linters config

**Comment by WALWALASAFI** [comment]
@dear ZohalMirkhel,
look at my project darling

**Comment by WALWALASAFI** [comment]
@ZohalMirkhel 
darling kindly look at  to my project

**Comment by ZohalMirkhel** [comment]
Dear @WALWALASAFI, I reviewed your code/project and noticed that your HTML could be cleaner. It would be better to use two spaces instead of four. Additionally, you're missing a linters file, which may not be important, though I am not sure. Your website is functioning well, but the heading disappears into the upper border when the screen is resized to a smaller size. You might want to address this issue, though I don't know if it's a significant problem.
Happy coding!!

**Comment by WALWALASAFI** [comment]
Hi dear sir @ahzamir ,
i hope you are fine and great.
have a look to my project however i have solved my partners feedback.
hopefully  be acceptable and  approvable for you dear sir
thanks in advance!

**Review by ahzamir — APPROVED** [review]
### Hi @WALWALASAFI 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text on it with a screenshot.

- Well Done great design Implemented. 🎯🎉👍
image

# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

WinkThumbsUpGIF

 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Roman Numeral Converter project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
✔️Your repo has a professional README.md file
✔️Your repo have been reviewed by your partner
✔️Your design is responsive

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @ahzamir in your question so I can receive the notification.**

**Pull request merged**
